GET http://localhost:5129/games


POST http://localhost:5129/games

Content-Type:  application/json
{
 "name":"Minecraft",
  "genre": "Kids and family",
  "price": 19.99,
  "releaseDate": "2011-11-18"
}